INSERT INTO BENEFICIARIES VALUES(random_uuid(), 'Jim')
INSERT INTO BENEFICIARIES VALUES(random_uuid(), 'Sam')
INSERT INTO BENEFICIARIES VALUES(random_uuid(), 'Tom')
INSERT INTO BENEFICIARIES VALUES(random_uuid(), 'Kate')