CREATE TABLE IF NOT EXISTS BENEFICIARIES (
    id UUID PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    number UUID PRIMARY KEY,
    beneficiary UUID NOT NULL,
    pin VARCHAR(255) NOT NULL,
    balance NUMBER(20, 4) DEFAULT 0.0,
    FOREIGN KEY(beneficiary) REFERENCES BENEFICIARIES(id)
);


CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    id UUID PRIMARY KEY,
    account UUID NOT NULL,
    receiver UUID,
    operation VARCHAR(50) NOT NULL,
    transaction_sum NUMBER(20, 4) NOT NULL,
    transaction_timestamp TIMESTAMP NOT NULL,
    FOREIGN KEY(account) REFERENCES ACCOUNTS(number),
    FOREIGN KEY(receiver) REFERENCES ACCOUNTS(number)
);